from .consent_copies_form import ConsentCopiesForm
from .consent_copies_form import ConsentImageForm
from .consent_copies_form import SpecimenConsentImageForm
from .omang_copies_form import OmangCopiesForm
from .omang_copies_form import NationalIdentityImageForm
