from .consent_copies_form import ConsentCopiesForm
from .consent_copies_form import ConsentImageForm
from .consent_copies_form import SpecimenConsentImageForm
from .consent_copies_form import NationalIdentityImageForm
